SITE_URL = "infhub.heroku.com"

PROJECT_DESCRIPTION_MAX_LENGTH = 1500
PROJECT_TITLE_MAX_LENGTH = 80
PERSON_ABOUT_MAX_LENGTH = 300
PERSON_NAME_MAX_LENGTH = 50
PERSON_NICK_MAX_LENGTH = 50
MINIMUM_YEAR_ACCEPTABLE = 1989
MAX_FILE_SIZE_MB = 5
MAX_IMAGE_FILE_SIZE_MB = 10
PEOPLE_PER_PAGE = 20
PROJECTS_PER_PAGE = 15